### ISSUE TITLE
[Bug]: 使用release镜像部署GLM4.7没有报错，日志中断

### ISSUE THREAD

**Issue by Liears** [jd-opensource/xllm#758]
### Your environment

A2
`quay.io/jd_xllm/xllm-ai:xllm-0.7.2-release-hb-rc2-arm`
启动命令
```
#!/bin/bash

set -e

rm -rf core.*

export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
export LD_PRELOAD=/usr/lib64/libtcmalloc.so.4:$LD_PRELOAD
# export MALLOC_ARENA_MAX=4
# # 3. 可选：扩大 TLS 缓存大小（部分系统需要）
# export LD_ASSUME_KERNEL=3.10.0
# export TLS_MINIMAL=0

source /usr/local/Ascend/ascend-toolkit/set_env.sh 
source /usr/local/Ascend/nnal/atb/set_env.sh
export ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export HCCL_IF_BASE_PORT=43432  # HCCL 通信基础端口

MODEL_PATH="./GLM-4.7-W8A8"               # 模型路径
MASTER_NODE_ADDR="127.0.0.1:9748"                  # Master 节点地址（需全局一致）
START_PORT=18000                                   # 服务起始端口
START_DEVICE=0                                     # 起始逻辑设备号
LOG_DIR="log"                                      # 日志目录
NNODES=8                                           # 节点数（当前脚本启动 1 个进程）

mkdir -p $LOG_DIR

for (( i=0; i<$NNODES; i++ ))
do
  PORT=$((START_PORT + i))
  DEVICE=$((START_DEVICE + i))
  LOG_FILE="$LOG_DIR/node_$i.log"
  /usr/local/bin/xllm \
    --model $MODEL_PATH \
    --model_id GLM \
    --devices="npu:$DEVICE" \
    --port $PORT \
    --master_node_addr=$MASTER_NODE_ADDR \
    --nnodes=$NNODES \
    --max_memory_utilization=0.86 \
    --max_tokens_per_batch=131072 \
    --max_seqs_per_batch=32 \
    --block_size=128 \
    --communication_backend="hccl" \
    --enable_prefix_cache=false \
    --enable_chunked_prefill=true \
    --enable_schedule_overlap=true \
    --enable_shm=true \
    --node_rank=$i \ > $LOG_FILE 2>&1 &
done
```

### 🐛 Describe the bug

日志中断且未报错
```
I20260121 05:37:27.984117  2043 xllm.cpp:130] set worker role to remote worker
I20260121 05:37:27.985280  2043 master.cpp:56] Master init options: Options: [model_path: /mnt2/metis/huggface_models/ZhipuAI/GLM-4.7-W8A8, devices: npu:0, draft_model_path: , draft_devices: npu:0, backend: llm, limit_image_per_prompt: 4, block_size: 128, max_cache_size: 0, max_memory_utilization: 0.86, enable_prefix_cache: 0, max_tokens_per_batch: 131072, max_seqs_per_batch: 32, max_tokens_per_chunk_for_prefill: 131072, num_speculative_tokens: 0, num_request_handling_threads: 4, communication_backend: hccl, rank_tablefile: , expert_parallel_degree: 0, task_type: generate, enable_mla: 0, enable_chunked_prefill: 1, master_node_addr: 100.102.191.169:9748, instance_role: DEFAULT, device_ip: , transfer_listen_port: 26000, nnodes: 8, node_rank: 0, enable_schedule_overlap: 1, enable_disagg_pd: 0, enable_pd_ooc: 0, kv_cache_transfer_mode: PUSH, etcd_addr: , enable_service_routing: 0, enable_cache_upload: 0, enable_kvcache_store: 0, store_protocol: tcp, store_master_server_entry: , store_metadata_connstring: , enable_multi_stream_parallel: 0, enable_continuous_kvcache: 0, disable_ttft_profiling: 0, enable_forward_interruption: 0]
I20260121 05:37:27.985886  2043 master.cpp:91] Creating engine with devices: npu:0
I20260121 05:37:27.986565  2043 dist_manager.cpp:101] Multi-node serving world_size = 8, each_node_ranks = 1, current node rank = 0, nnodes = 8, dp_size = 1, ep_size = 1, tp_size = 8
```

**Comment by JimHsiung** [comment]
Hi, try running this command before starting xllm to initialize the devices: `python -c "import torch_npu; for i in range(16): torch_npu.npu.set_device(i)"`

**Comment by rauletorresc** [comment]
> Hi, try running this command before starting xllm to initialize the devices: `python -c "import torch_npu; for i in range(16): torch_npu.npu.set_device(i)"`

Thanks for the solution. I have to correct it to align to proper Python syntax: `python -c 'import torch_npu; [torch_npu.npu.set_device(i) for i in range(16)]'`, but it is working now, the server now reaches this point:

`I20260122 22:29:54.097396  1266 xllm_server.cpp:59] Brpc Server started on port 23333, idle_timeout_s: -1, num_threads: 32`

Is that the intended output?

**Comment by JimHsiung** [comment]
> > Hi, try running this command before starting xllm to initialize the devices: `python -c "import torch_npu; for i in range(16): torch_npu.npu.set_device(i)"`
> 
> Thanks for the solution. I have to correct it to align to proper Python syntax: `python -c 'import torch_npu; [torch_npu.npu.set_device(i) for i in range(16)]'`, but it is working now, the server now reaches this point:
> 
> `I20260122 22:29:54.097396 1266 xllm_server.cpp:59] Brpc Server started on port 23333, idle_timeout_s: -1, num_threads: 32`
> 
> Is that the intended output?

Yes, this means the service has been successfully started.
