### ISSUE TITLE
Bug: MTP + Graph 模式下 q_cu_seq_lens 形状不匹配导致崩溃

### ISSUE THREAD

**Issue by QwertyJack** [jd-opensource/xllm#790]
## 问题概述
MTP 模型在 NPU + Graph 模式下运行时，当 `enable_atb_spec_kernel=false` 且 batch_size > 1 时，服务在 MTP 验证阶段崩溃。

**影响范围：** 所有使用 MTP + Graph 模式的模型（GLM-4.7、DeepSeek v3.2 等）

## 环境信息
- **平台**: Linux 5.10.0 aarch64 (NPU)
- **模型**: GLM-4.7 + GLM-4.7-MTP
- **配置**: `enable_atb_spec_kernel=false`, `num_speculative_tokens=1`

## 复现条件
1. 使用 MTP 模型配置启动服务
2. 设置 `--enable_atb_spec_kernel=false`
3. 发送 2+ 个并发请求（使 batch_size > 1）

## 错误信息
```
terminate called after throwing an instance of 'c10::Error'
  what():  copy_d2d_baseformat_opapi: NPU function error: aclnnInplaceCopy failed

EZ1001: 2 and 4 cannot broadcast.
The size of tensor self [4] must match the size of tensor src [2].
```

## 调用栈
```
xllm::npu::GraphPersistentParam::update()     <-- 崩溃点
xllm::npu::AclGraph::capture()
xllm::npu::AclGraphExecutorImpl::run()
xllm::Executor::forward()
xllm::LLMWorkerImpl::step()
```

### 问题本质
在 MTP speculative validation 模式下，当 `enable_atb_spec_kernel=false` 时：
- `num_sequences` 扩展为 `total_num_val_tokens = num_sequences * (num_speculative_tokens + 1)`
- `q_seq_lens` 和 `kv_seq_lens` 在 `prepare_validate_inputs()` 中被正确重建
- **但 `q_cu_seq_lens` 未被重建**，保留了从 `params_utils.cpp` 传入的原始大小

### Debug 日志验证
```
[DEBUG] actual_batch_size(num_sequences)=4
        q_seq_lens.size(0)=4      ✓ (正确扩展)
        kv_seq_lens.size(0)=4     ✓ (正确扩展)
        q_cu_seq_lens.size(0)=2   ✗ (未扩展，来自原始 input)
```

### 代码路径
1. `params_utils.cpp:71-72`: 为所有模型创建 `q_cu_seq_lens`（size = num_sequences）
2. `speculative_worker_impl.cpp:499`: `validate_input = input.to(device_, dtype_)` 复制整个 input，包括 `q_cu_seq_lens`
3. `speculative_worker_impl.cpp:587-594`: 当 `enable_atb_spec_kernel=false` 时，`num_sequences` 扩展为 `total_num_val_tokens`
4. `acl_graph_executor_impl.cpp:204-205`: 使用 `actual_batch_size` 切片，但 `q_cu_seq_lens.size(0)` 仍为原始值

### 崩溃触发
```cpp
q_cu_seq_lens_.slice(/*dim=*/0, /*start=*/0, /*end=*/actual_batch_size)  // actual_batch_size=4
    .copy_(params.q_cu_seq_lens, /*non_blocking=*/true);  // size=2 → CRASH
```

## 修复方案

在 `speculative_worker_impl.cpp` 的 `prepare_validate_inputs()` 中重建 `q_cu_seq_lens`：

```cpp
if (!input_params.q_seq_lens_vec.empty()) {
  std::vector<int32_t> q_cu_seq_lens(input_params.q_seq_lens_vec.size());
  std::partial_sum(input_params.q_seq_lens_vec.begin(),
                   input_params.q_seq_lens_vec.end(),
                   q_cu_seq_lens.begin());
  input_params.q_cu_seq_lens = torch::tensor(q_cu_seq_lens, int_options);
} else {
  input_params.q_cu_seq_lens = torch::Tensor();
}
```

## 验证步骤
1. 使用 MTP 配置启动服务，设置 `--enable_atb_spec_kernel=false`
2. 发送多个并发请求
3. 确认服务稳定运行，无崩溃

## 相关 PR
- #791 - 修复提交

**Comment by Liears** [comment]
The same issue is analyzed very thoroughly.

**Comment by zhang-minchao** [comment]
能确定是在复制q_cu_seq_lens_时吗？很有可能是复制q_seq_lens时就有的。因为GLM4.7 MTP时应该不会产生q_cu_seq_lens，也就不会复制q_cu_seq_lens_
```cpp
if (params.q_cu_seq_lens.defined()) {
    // Lazy initialization: if q_cu_seq_lens_ is not initialized, initialize it
    if (q_cu_seq_lens_.numel() == 0) {
      const int64_t max_seqs_per_batch = options_.max_seqs_per_batch();
      q_cu_seq_lens_ = torch::zeros({max_seqs_per_batch + 1},
                                    torch::dtype(torch::kInt).device(device_));
    }
    // Copy data
    q_cu_seq_lens_.slice(/*dim=*/0, /*start=*/0, /*end=*/actual_batch_size)
        .copy_(params.q_cu_seq_lens, /*non_blocking=*/true);
  }
```

**Comment by QwertyJack** [comment]
@zhang-minchao 感谢您的审查和问题！经过本地测试验证，现在可以确认根因。

## 回答您的问题

> 能确定是在复制q_cu_seq_lens_时吗？

**是的，已确认。** 通过添加 debug 日志并复现崩溃：

```
[DEBUG] actual_batch_size(num_sequences)=4
        q_seq_lens.size(0)=4      ✓
        kv_seq_lens.size(0)=4     ✓
        q_cu_seq_lens.size(0)=2   ✗ ← 问题所在
```

崩溃信息：`The size of tensor self [4] must match the size of tensor src [2]`

## 根因分析（更新）

您说得对，GLM-4.7 本身不使用 `q_cu_seq_lens`（只有 DeepSeek v3.2 使用）。但关键是：

1. `params_utils.cpp:71-72` 为所有模型创建 `q_cu_seq_lens`（通过 partial_sum）
2. `prepare_validate_inputs()` 复制 input 到 validate_input 时，`q_cu_seq_lens` 被带入
3. 当 `enable_atb_spec_kernel=false` 时，batch 扩展但 `q_cu_seq_lens` 未重建
4. `q_cu_seq_lens.defined()` 返回 true，进入复制逻辑，触发崩溃

## 复现条件

- `enable_atb_spec_kernel=false`
- batch_size > 1（多个并发请求）
- MTP 模式

## 修复方案（已更新 PR #791）

1. **根因修复**：在 `prepare_validate_inputs()` 中重建 `q_cu_seq_lens`
2. **防御性修复**：`acl_graph_executor_impl.cpp` 使用实际张量大小

感谢您指出需要与 DeepSeek v3.2 MTP 开发同事对齐的问题。如果有进一步的要求，请告知。

**Comment by QwertyJack** [comment]
This issue has been fixed by #796 (DeepSeek-V3.2 MTP).

The fix in #796 rebuilds `q_cu_seq_lens` after batch expansion in `prepare_validate_inputs()`, which resolves the tensor shape mismatch for all MTP models (including GLM-4.7) when `enable_atb_spec_kernel=false`.

Verified locally: GLM-4.7 + MTP + Graph mode now works correctly on upstream/main. Closing this issue.
